# 5x5 cinema seating
# A = Available, B = Booked
cinema_seats = [
   ['A', 'A', 'B', 'A', 'A'],
   ['A', 'B', 'B', 'A', 'A'],
   ['A', 'A', 'A', 'A', 'B'],
   ['B', 'A', 'A', 'A', 'A'],
   ['A', 'B', 'A', 'A', 'A']
]

def seats_total(seats):
   ...
   return ...

def seats_available(seats):
   ...
   ...
   return ...

def seats_booked(seats):
   ...
   ...
   return ...

def seat_status(seats, row, place):
   ...
   ...
   return ...

print('CINEMA INFORMATION TABLE')
print('Total seats:',...)
print('Seats available:',...)
print('Seats booked:', ...)
print('Seat in row 1, place 1:', ...)
print('Seat in row 5, place 5:', ...)
print('Seat in row 3, place 5:', ...)